name: Setup Python Action
description: A GitHub Action that wraps actions/setup-python and adds some useful functionality.
runs:
  using: composite
  steps:
    # We cannot reference $GITHUB_ACTION_PATH in the path to other actions, but we can symlink it to a known location and then reference that location.
    # This ensures that the path to the action stays the same even if the runner starts storing actions in different locations or the action is being run from a fork with a different name.
    - name: Configure Subactions
      shell: sh
      run: ln -s "$GITHUB_ACTION_PATH" "./../_setup-python-action"
    - name: Setup Task
      uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
      with:
        repo-token: ${{ inputs.token }}
    - name: Prepare Python
      id: prepare-python
      uses: ./../_setup-python-action/subactions/prepare/
      with:
        python-version-path: ${{ inputs.python-version-path }}
    - name: Setup Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: ${{ steps.prepare-python.outputs.python-version }}
    - name: Install Base Dependencies
      shell: sh
      run: python3 -m pip install --requirement ./base-dependencies.txt
inputs:
  python-version-path:
    description: The path to the `.python-version` file.
    required: true
    default: ./.python-version
  token:
    description: A token for GitHub API access. It does not need any permissions, it's just used to avoid rate limiting.
    required: true
    default: ${{ github.token }}
