name: Setup Python Action - Prepare
description: A preparation step that gathers information and sets up dependencies.
runs:
  using: node20
  main: ./../../bootstrap-shim.js
  post: ./../../build/post.js
inputs:
  python-version-path:
    description: The path to the `.python-version` file.
    required: true
    default: ./.python-version
